import type { Metadata } from "next";
//import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navigation } from "@/components/navigation";
import { Roboto } from 'next/font/google'
import { SearchProvider } from "./search-context"

const roboto = Roboto({ weight: ['400', '500', '700'], subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Direktori UMKM",
  description: "Generated by create next app",
    icons: {
    icon: "/logo.jpg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="bg-black text-white antialiased" style={{ fontFamily: roboto.style.fontFamily }}
      >
        <SearchProvider>
        <Navigation/>
        {children}
        </SearchProvider>
      </body>
    </html>
  );
}
