export const umkmData = [
  {
    id: "1",
    name: "Kedai Aduhai",
    category: "Makanan",
    description: "Kedai Aduhai adalah tempat makan yang menyajikan prasmanan dengan berbagai pilihan hidangan lezat dan bergizi.",
    address: "Jl. Abimanyu No.3, Ngebel, Tamantirto, Kec. Kasihan, Kabupaten Bantul, Daerah Istimewa Yogyakarta 55183",
    hours: "07:00 - 15:00",
    rating: 4.6,
    reviews: 19,
    image: "/traditional-coffee-shop-interior.jpg",
    gallery: ["/traditional-coffee-shop-interior.jpg", "/coffee-cups-and-beans.jpg", "/cozy-coffee-shop-ambiance.jpg"],
  },
  {
    id: "2",
    name: "Wamindo Montekar 7",
    category: "Makanan",
    description: "Warmindo Motekar 7 adalah warung makan bergaya warung Indomie modern.",
    address: "JL. Geblagan, Tamantirto, Kec. Kasihan, Kabupaten Bantul, Daerah Istimewa Yogyakarta 55184",
    hours: "00:00 - 23:59",
    rating: 4.5,
    reviews: 896,
    image: "/bakso-meatball-soup.jpg",
    gallery: ["/bakso-meatball-soup-bowl.jpg", "/bakso-restaurant-interior.jpg", "/bakso-ingredients-preparation.jpg"],
  },
  {
    id: "3",
    name: "Agas Geprek",
    category: "Makanan",
    description: "Agas Geprek adalah tempat makan yang menyajikan ayam geprek dengan cita rasa pedas gurih dan sambal khas yang bisa disesuaikan tingkat kepedasannya. Dimasak dengan bumbu rempah pilihan dan disajikan hangat.",
    address: "Jl. Ngebel, Tamantirto, Kec. Kasihan, Kabupaten Bantul, Daerah Istimewa Yogyakarta 55184",
    hours: "09:00 - 18:00",
    rating: 4.4,
    reviews: 94,
    image: "/beauty-salon-interior.png",
    gallery: ["/beauty-salon-interior-modern.jpg", "/hair-styling-station.png", "/spa-treatment-room.png"],
  },
  {
    id: "4",
    name: "Warteg Kharisma Bahari Ngebel - UMY",
    category: "Makanan",
    description: "Warteg (Warung Tegal) adalah tempat makan khas Indonesia yang menyajikan berbagai masakan rumahan sederhana namun menggugah selera. Dikenal dengan porsi melimpah dan harga terjangkau.",
    address: "Jl. Ngebel, Tamantirto, Kec. Kasihan, Kabupaten Bantul, Daerah Istimewa Yogyakarta 55184",
    hours: "06:30 - 00:00",
    rating: 3.3,
    reviews: 16,
    image: "/batik-fabric-store.jpg",
    gallery: ["/batik-fabric-display.jpg", "/traditional-batik-patterns.jpg", "/batik-shop-interior.jpg"],
  },
  {
    id: "5",
    name: "Sate Taichan Langgeng",
    category: "Makanan",
    description: "Sate Taichan Langgeng adalah tempat makan yang menyajikan sate ayam tanpa bumbu kacang khas Taichan dengan cita rasa gurih pedas yang menggugah selera.",
    address: "Jl. Patriot Bangsa, Geblagan, Tamantirto, Kec. Kasihan, Kabupaten Bantul, Daerah Istimewa Yogyakarta 55184",
    hours: "11:00 - 22:00",
    rating: 4.8,
    reviews: 496,
    image: "/traditional-indonesian-food.jpg",
    gallery: ["/indonesian-home-cooked-meals.jpg", "/warung-makan-interior.jpg", "/placeholder.svg?height=400&width=600"],
  },
  {
    id: "6",
    name: "Dingo Coffee-UMY",
    category: "Makanan & Minuman",
    description: "Cafe modern yang menawarkan berbagai pilihan kopi spesial, minuman non-kopi, dan camilan lezat. Terletak strategis di lingkungan kampus.",
    address: "Jl. Brawijaya, Geblagan, Tamantirto, Kec. Kasihan, Kabupaten Bantul, Daerah Istimewa Yogyakarta 55184",
    hours: "08:00 - 23:00",
    rating: 4.8,
    reviews: 236,
    image: "/placeholder.svg?height=300&width=400",
    gallery: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
  },
  {
    id: "7",
    name: "Karib Kafe",
    category: "Makanan & Minumana",
    description: "Tempat nongkrong modern yang menawarkan kopi berkualitas, minuman segar, dan berbagai camilan lezat. Suasana kafe yang hangat dan nyaman membuatnya cocok untuk bersantai, belajar, bekerja, atau berkumpul bersama teman..",
    address: "Jl. Bunga, Geblagan, Tamantirto, Kec. Kasihan, Kabupaten Bantul, Daerah Istimewa Yogyakarta 55184",
    hours: "09:00 - 23:00",
    rating: 4.7,
    reviews: 93,
    image: "/placeholder.svg?height=300&width=400",
    gallery: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
  },
  {
    id: "8",
    name: "Koat Kopi Tamantirto",
    category: "Makanan & Minuman",
    description: "Cafe hangat yang menyajikan kopi berkualitas tinggi dan minuman kreatif untuk dinikmati kapan saja. Terletak strategis, kafe ini menjadi tempat favorit bagi pengunjung yang ingin bersantai, belajar, bekerja, atau berkumpul bersama teman.",
    address: "Jl. Brajan Lor No.108, Brajan, Tamantirto, Kec. Kasihan, Kabupaten Bantul, Daerah Istimewa Yogyakarta 55184",
    hours: "09:00 - 00.30:",
    rating: 4.6,
    reviews: 712,
    image: "/placeholder.svg?height=300&width=400",
    gallery: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
  },
  {
    id: "9",
    name: "Mie Ayam Palembang Afui",
    category: "Makanan",
    description: "Mie Ayam Palembang Afui adalah tempat makan spesialis mie ayam dengan cita rasa khas Palembang. Setiap porsi mie disajikan dengan ayam suwir berbumbu rempah, kuah kaldu gurih, dan taburan bawang goreng yang membuat rasanya begitu lezat dan menggugah selera.",
    address: "Gg. Damai, Gatak, Tamantirto, Kec. Kasihan, Kabupaten Bantul, Daerah Istimewa Yogyakarta 55184",
    hours: "09:00 - 18:45",
    rating: 4.5,
    reviews: 547,
    image: "/placeholder.svg?height=300&width=400",
    gallery: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
  },
  {
    id: "10",
    name: "Utama Sembako dan Sayuran",
    category: "Makanan & Minuman",
    description: "Toko Sembako adalah tempat belanja kebutuhan pokok sehari-hari yang menyediakan berbagai produk mulai dari beras, minyak, gula, mie instan, susu, hingga bahan kebutuhan rumah tangga lainnya.",
    address: "Jl. Rajawali, Ngebel, Ambarketawang, Kec. Gamping, Kabupaten Bantul, Daerah Istimewa Yogyakarta 55294",
    hours: "05:50 - 22:00",
    rating: 4.6,
    reviews: 145,
    image: "/placeholder.svg?height=300&width=400",
    gallery: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
  },
]
