export const umkmData = [
  {
    id: "1",
    name: "Warung Kopi Tradisional",
    category: "Minuman",
    description: "Kopi tradisional dengan cita rasa autentik yang telah melayani pelanggan setia selama 15 tahun.",
    address: "Jl. Merdeka No. 45, Jakarta Pusat",
    phone: "+62-21-1234567",
    hours: "06:00 - 22:00",
    rating: 4.8,
    reviews: 234,
    image: "/traditional-coffee-shop-interior.jpg",
    gallery: ["/traditional-coffee-shop-interior.jpg", "/coffee-cups-and-beans.jpg", "/cozy-coffee-shop-ambiance.jpg"],
  },
  {
    id: "2",
    name: "Bakso Legendaris Pak Haji",
    category: "Makanan",
    description: "Bakso berkualitas tinggi dengan resep turun temurun yang gurih dan lezat.",
    address: "Jl. Ahmad Yani No. 12, Bandung",
    phone: "+62-274-5678901",
    hours: "10:00 - 21:00",
    rating: 4.9,
    reviews: 456,
    image: "/bakso-meatball-soup.jpg",
    gallery: ["/bakso-meatball-soup-bowl.jpg", "/bakso-restaurant-interior.jpg", "/bakso-ingredients-preparation.jpg"],
  },
  {
    id: "3",
    name: "Salon Kecantikan Cantik Jaya",
    category: "Jasa",
    description: "Salon profesional dengan terapis berpengalaman dan produk berkualitas premium.",
    address: "Jl. Sudirman No. 78, Surabaya",
    phone: "+62-31-9876543",
    hours: "09:00 - 20:00",
    rating: 4.7,
    reviews: 189,
    image: "/beauty-salon-interior.png",
    gallery: ["/beauty-salon-interior-modern.jpg", "/hair-styling-station.png", "/spa-treatment-room.png"],
  },
  {
    id: "4",
    name: "Toko Batik Nusantara",
    category: "Retail",
    description: "Koleksi batik asli dengan desain tradisional dan modern yang memukau.",
    address: "Jl. Diponegoro No. 34, Yogyakarta",
    phone: "+62-274-5555555",
    hours: "08:00 - 18:00",
    rating: 4.6,
    reviews: 312,
    image: "/batik-fabric-store.jpg",
    gallery: ["/batik-fabric-display.jpg", "/traditional-batik-patterns.jpg", "/batik-shop-interior.jpg"],
  },
  {
    id: "5",
    name: "Warung Makan Sederhana",
    category: "Makanan",
    description: "Makanan rumahan dengan cita rasa autentik dan harga terjangkau untuk semua kalangan.",
    address: "Jl. Gatot Subroto No. 56, Medan",
    phone: "+62-61-4444444",
    hours: "07:00 - 20:00",
    rating: 4.5,
    reviews: 267,
    image: "/traditional-indonesian-food.jpg",
    gallery: ["/indonesian-home-cooked-meals.jpg", "/warung-makan-interior.jpg", "/placeholder.svg?height=400&width=600"],
  },
  {
    id: "6",
    name: "Jus Segar Tropis",
    category: "Minuman",
    description: "Minuman segar dari buah-buahan pilihan tanpa pengawet dan pewarna buatan.",
    address: "Jl. Imam Bonjol No. 23, Semarang",
    phone: "+62-24-3333333",
    hours: "08:00 - 19:00",
    rating: 4.8,
    reviews: 198,
    image: "/placeholder.svg?height=300&width=400",
    gallery: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
  },
  {
    id: "7",
    name: "Tukang Jahit Bapak Amin",
    category: "Jasa",
    description: "Jasa jahit custom dengan hasil rapi dan desain sesuai keinginan pelanggan.",
    address: "Jl. Hayam Wuruk No. 67, Malang",
    phone: "+62-341-2222222",
    hours: "09:00 - 17:00",
    rating: 4.7,
    reviews: 145,
    image: "/placeholder.svg?height=300&width=400",
    gallery: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
  },
  {
    id: "8",
    name: "Toko Elektronik Maju Jaya",
    category: "Retail",
    description: "Toko elektronik terpercaya dengan harga kompetitif dan garansi resmi.",
    address: "Jl. Veteran No. 89, Palembang",
    phone: "+62-711-1111111",
    hours: "09:00 - 21:00",
    rating: 4.6,
    reviews: 423,
    image: "/placeholder.svg?height=300&width=400",
    gallery: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
  },
  {
    id: "9",
    name: "Restoran Seafood Pantai",
    category: "Makanan",
    description: "Restoran seafood dengan menu beragam dan bahan-bahan segar dari laut.",
    address: "Jl. Pantai Indah No. 12, Bali",
    phone: "+62-361-9999999",
    hours: "11:00 - 23:00",
    rating: 4.9,
    reviews: 567,
    image: "/placeholder.svg?height=300&width=400",
    gallery: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
  },
  {
    id: "10",
    name: "Klinik Kesehatan Sehat Selalu",
    category: "Jasa",
    description: "Klinik kesehatan dengan dokter berpengalaman dan fasilitas medis lengkap.",
    address: "Jl. Kesehatan No. 45, Makassar",
    phone: "+62-411-8888888",
    hours: "08:00 - 18:00",
    rating: 4.8,
    reviews: 334,
    image: "/placeholder.svg?height=300&width=400",
    gallery: [
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
      "/placeholder.svg?height=400&width=600",
    ],
  },
]
